# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=40)),
            ],
        ),
    ]
