# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 8, 3, 11, 44, 133000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
