# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0002_userrole_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='realname',
            field=models.CharField(default=datetime.datetime(2016, 3, 10, 18, 11, 58, 801000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
